### PR TITLE
FIX - duration is not respected

### PR DESCRIPTION
**Pull request by Fr33maan**
As each scroll was using a different value for `from`, the easing function was not computing the correct new scroll value

### CODE REVIEW

**Comment by mkay581** [comment]
Thanks for opening this! I think I understand the issue based on your description, but to be sure, do you mind posting an example of your specific usage that uncovered this bug? It would also help for testing purposes.

**Comment by l1br3** [comment]
Sorry I don't have more time for this.

Basicaly what you do is computing with the wrong value which causes the 
scroll to arrive to end much more before duration.
Because you reduce the size of the scroll to operate (because you update 
the from instead of keeping it) and increase the proportion of distance 
to scroll (because of the ease), the scrolling speed is exponential.

A minimal setup will be enough, just console.log your value and you will 
see the bug.
Just try to put high value in duration and you will see it's not respected.

**Comment by mkay581** [comment]
No worries. I got to the root of it and added a quick test case. Once PR passes, I'll merge this and publish it in a new minor version.

**Comment by mkay581** [comment]
@l1br3 this has been included in version 2.2.0 of the package. Thanks again for your help!

**Pull request merged**
